apiVersion: apps/v1
kind: Deployment
metadata:
  name: gin-demo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: gin-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gin-demo
    spec:
      restartPolicy: Always
      containers:
        - name: gin-demo
          image: gin-demo:test
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 100Mi
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          args:
            - "--config=/configs"
          volumeMounts:
            - name: config-volume
              mountPath: /configs/config.yaml
              subPath: config.yaml
            - name: log-volume
              mountPath: /logs
      volumes:
        - name: config-volume
          configMap:
            name: gin-demo
        - name: log-volume
          emptyDir: {}
