# This is a basic workflow to help you get started with Actions

name: DEVCI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [feature/**]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_UERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true

      - name: Get repo info
        run: |
          REPO_NAME=${GITHUB_REPOSITORY#GITHUB_REPOSITORY_OWNER};
          case $GITHUB_REF in refs/heads/*)
            GITHUB_BRANCH=${GITHUB_REF#refs/heads/};
          case $GITHUB_REF in refs/tags/*)
            GITHUB_TAG=${GITHUB_REF#refs/tags/};

      # Runs a set of commands using the runners shell
      - name: build image
        run: |
          make pre-build
          docker build -t ${{ REPO_NAME }}:${{ GITHUB_BRANCH }} .
          docker tag gin-demo:dev ${{ secrets.DOCKER_UERNAME }}/${{ REPO_NAME }}:sha-${{ github.sha }}
          docker push ${{ secrets.DOCKER_UERNAME }}/${{ REPO_NAME }}:sha-${{ github.sha }}
          docker push ${{ secrets.DOCKER_UERNAME }}/${{ REPO_NAME }}:${{ GITHUB_BRANCH }}

      # - name: Trigger CI
      #   uses: InformaticsMatters/trigger-ci-action@1.0.1
      #   with:
      #     ci-owner: znqerz
      #     ci-repository: gin-demo-kustomize
      #     ci-ref: refs/heads/master
      #     ci-user: znqerz
      #     ci-user-token: ${{ secrets.CI_TOKEN }}
      #     ci-name: CI
      #     ci-inputs: >-
      #       image=${{ secrets.DOCKER_UERNAME }}/gin-demo
      #       sha-tag=sha-${{ github.sha }}
