name: Dev CI

on:
  push:
    branches:
      - "feature/**"

  workflow_dispatch:

env:
  DOCKER_REGISTRY: docker.io/${{ secrets.DOCKER_UERNAME }}

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.DOCKER_REGISTRY }}/gin-demo
          tags: |
            type=sha

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_UERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Trigger CI
        if: success()
        uses: InformaticsMatters/trigger-ci-action@1.0.1
        with:
          ci-owner: znqerz
          ci-repository: gin-demo-manifests
          ci-ref: refs/heads/main
          ci-user: znqerz
          ci-user-token: ${{ secrets.CI_TOKEN }}
          ci-name: BOT-CI
          ci-inputs: >-
            image=${{ env.DOCKER_REGISTRY }}/gin-demo
            tag=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
            env=local
            src=local
