name: Release CI

on:
  push:
    tags:
      - "*"
  # pull_request:
  #   branches: [main]
  #   types: [closed]

  workflow_dispatch:

env:
  DOCKER_REGISTRY: docker.io/${{ secrets.DOCKER_UERNAME }}

jobs:
  build_image:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.DOCKER_REGISTRY }}/gin-demo
          tags: |
            type=semver,pattern={{version}}

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_UERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # - name: build image
      #   run: |
      #     make pre-build
      #     GITHUB_BRANCH=$(echo $GITHUB_REF | sed -e "s#refs/tags/##g")
      #     GITHUB_SHA_SHORT=$(git rev-parse --short HEAD)
      #     docker build -t gin-demo:$GITHUB_BRANCH .
      #     docker tag gin-demo:$GITHUB_BRANCH ${{ secrets.DOCKER_UERNAME }}/gin-demo:sha-$GITHUB_SHA_SHORT
      #     docker tag gin-demo:$GITHUB_BRANCH ${{ secrets.DOCKER_UERNAME }}/gin-demo:$GITHUB_BRANCH
      #     docker push ${{ secrets.DOCKER_UERNAME }}/gin-demo:sha-$GITHUB_SHA_SHORT
      #     docker push ${{ secrets.DOCKER_UERNAME }}/gin-demo:$GITHUB_BRANCH

      - name: Trigger CI
        uses: InformaticsMatters/trigger-ci-action@1.0.1
        with:
          ci-owner: znqerz
          ci-repository: gin-demo-manifests
          ci-ref: refs/heads/main
          ci-user: znqerz
          ci-user-token: ${{ secrets.CI_TOKEN }}
          ci-name: BOT-CI
          ci-inputs: >-
            image=${{ env.DOCKER_REGISTRY }}/gin-demo
            sha-tag=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
