# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
    tags:
      - "v.*"
  # pull_request:
  #   branches: [main]
  #   types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  if_merged:
    # if: github.event.pull_request.merged == true
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_UERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true

      # Runs a set of commands using the runners shell
      - name: build image
        run: |
          make pre-build
          GITHUB_BRANCH=$(echo $GITHUB_REF | sed -e "s#refs/heads/feature/##g")
          GITHUB_SHA_SHORT=$(git rev-parse --short HEAD)
          docker build -t gin-demo:$GITHUB_BRANCH .
          docker tag gin-demo:$GITHUB_BRANCH ${{ secrets.DOCKER_UERNAME }}/gin-demo:sha-$GITHUB_SHA_SHORT
          docker tag gin-demo:$GITHUB_BRANCH ${{ secrets.DOCKER_UERNAME }}/gin-demo:$GITHUB_BRANCH
          docker push ${{ secrets.DOCKER_UERNAME }}/gin-demo:sha-$GITHUB_SHA_SHORT
          docker push ${{ secrets.DOCKER_UERNAME }}/gin-demo:$GITHUB_BRANCH

      - name: Trigger CI
        uses: InformaticsMatters/trigger-ci-action@1.0.1
        with:
          ci-owner: znqerz
          ci-repository: gin-demo-manifests
          ci-ref: refs/heads/main
          ci-user: znqerz
          ci-user-token: ${{ secrets.CI_TOKEN }}
          ci-name: BOT-CI
          ci-inputs: >-
            image=${{ secrets.DOCKER_UERNAME }}/gin-demo
            sha-tag=sha-${{ github.sha }}
